import type { PortfolioReport } from '../types/analysis';

export function formatReportToMarkdown(report: PortfolioReport): string {
  const { facts, scoring, recruiter, roasts, roadmap } = report;

  return `# 🚀 Repozyn AI: GitHub Portfolio Audit & Roast
**Target User:** [@${facts.username}](${facts.profileUrl}) (${facts.name || 'Anonymous'})  
**Portfolio Health Grade:** **${scoring.grade}** (${scoring.totalScore}/100)  
**Recruiter Archetype:** *${recruiter.archetype}*  
**Hireability Signal:** **${recruiter.hireabilitySignal}**  
**Audit Timestamp:** ${new Date(report.analyzedAt).toLocaleDateString()}

---

## 🟢 Verified GitHub Facts (Real REST API Data)
| Metric | Value |
| :--- | :--- |
| Public Repositories | ${facts.totalPublicRepos} (${facts.originalReposCount} original, ${facts.forkedReposCount} forks) |
| Total Stars Earned | ${facts.totalStarsEarned} ⭐ |
| Top Languages | ${facts.topLanguages.join(', ') || 'None detected'} |
| Description Coverage | ${facts.reposWithDescriptionPercentage}% (${facts.reposWithDescriptionCount}/${facts.analyzedReposCount} repos) |
| Open-Source License Coverage | ${facts.reposWithLicensePercentage}% (${facts.reposWithLicenseCount}/${facts.originalReposCount} original) |
| Live Demos / Pages | ${facts.reposWithDemoUrlCount} projects (${facts.reposWithDemoUrlPercentage}%) |
| Days Since Last Push | ${facts.daysSinceLastPush === 999 ? 'Unknown' : `${facts.daysSinceLastPush} days`} |
| Profile Bio & Links | Bio: ${facts.hasBio ? '✓' : '✗'}, Website: ${facts.hasWebsite ? '✓' : '✗'} |

---

## 🟣 Recruiter First Impression (The 10-Second Scan)
> "${recruiter.firstImpressionQuote}"
> — *Engineering Lead / Hiring Manager*

**Verdict:** ${recruiter.tenSecondVerdict}

### ✅ Recruiter Green Flags
${recruiter.greenFlags.map((f) => `- **${f.title}**: ${f.evidence}`).join('\n')}

### ⚠️ Recruiter Friction Points
${recruiter.redFlags.map((f) => `- **${f.title}**: ${f.evidence}`).join('\n')}

---

## 🌶️ Evidence-Based Roasts
${roasts
  .map(
    (r) => `### 🔥 ${r.title} [${r.severity.toUpperCase()}]
> "${r.roast}"
- **Evidence:** \`${r.evidence}\`
`
  )
  .join('\n')}

---

## 🛠️ Actionable Rescue Roadmap
${roadmap
  .map(
    (item, idx) => `### ${idx + 1}. ${item.title} (${item.priority.toUpperCase()} • ${item.effort})
${item.description}
- **Action Step:** ${item.actionStep}
`
  )
  .join('\n')}

---
*Generated by **Repozyn AI** — GitHub Roast and Rescue Engine. Built for the university hackathon.*
`;
}
